MODEL:
  META_ARCHITECTURE: "Visolo"
  WEIGHTS: "detectron2://ImageNetPretrained/torchvision/R-50.pkl"
  PIXEL_MEAN: [123.675, 116.280, 103.530]
  PIXEL_STD: [58.395, 57.120, 57.375]
  MASK_ON: True
  RESNETS:
    DEPTH: 50
    STRIDE_IN_1X1: False
    OUT_FEATURES: ["res2", "res3", "res4"]
  VISOLO:
    NUM_CLASSES: 80
DATASETS:
  TRAIN: ("coco_2017_train",)
  TEST: ("coco_2017_val",)
SOLVER:
  IMS_PER_BATCH: 16 # adjust as SAMPLING_FRAME_NUM increases
  BASE_LR: 0.0001
  STEPS: (300000,)
  MAX_ITER: 450000
  CHECKPOINT_PERIOD: 10000
  WARMUP_FACTOR: 1.0
  WARMUP_ITERS: 10
  WEIGHT_DECAY: 0.0001
  OPTIMIZER: "ADAMW"
  BACKBONE_MULTIPLIER: 0.1
  CLIP_GRADIENTS:
    ENABLED: True
    CLIP_TYPE: "full_model"
    CLIP_VALUE: 0.01
    NORM_TYPE: 2.0
INPUT:
  AUGMENTATIONS: []
  SAMPLING_FRAME_NUM: 3 # start with 1, then increase.
  MIN_SIZE_TRAIN_SAMPLING: "choice_by_clip"
  MIN_SIZE_TRAIN: (480, 512, 544, 576, 608, 640, 672)
  RANDOM_ROTATION: True
  CROP:
    ENABLED: True
    TYPE: "absolute"
    SIZE: (352, 624)
  FORMAT: "RGB"
DATALOADER:
  FILTER_EMPTY_ANNOTATIONS: False
  NUM_WORKERS: 8
VERSION: 2
